# Generated by Django 2.1.15 on 2020-06-05 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200605_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='club',
        ),
        migrations.RemoveField(
            model_name='clubgroup',
            name='club',
        ),
        migrations.RemoveField(
            model_name='event',
            name='club',
        ),
    ]
