# Generated by Django 2.1.15 on 2020-06-05 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200605_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='core.Club'),
        ),
        migrations.AddField(
            model_name='clubgroup',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.Club'),
        ),
        migrations.AddField(
            model_name='event',
            name='club',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.Club'),
        ),
    ]
