# Generated by Django 2.1.15 on 2020-06-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200606_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='lago pepito rio 2', max_length=100),
            preserve_default=False,
        ),
    ]
