# Generated by Django 2.1.15 on 2020-06-06 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='core.Event'),
        ),
    ]
