# Generated by Django 2.1.15 on 2020-06-09 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200609_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='votes',
            field=models.ManyToManyField(blank=True, null=True, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
