# Generated by Django 2.1.15 on 2020-06-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200609_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='votes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
